### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ds84182** [ds84182/msktool#1]
- [ ] 3D Scene abstraction so maps can be exported with collision geometry, cutscene triggers, and object positions
- [ ] Model file extraction to OBJ/3D Scene Object
- [ ] Command to msktool that exports an entire map with "speedrun relevant" information
